SUCCESS_MESSAGE_TTL = 3

# F
AUTO_ADVANCE_DEFAULT = False
SHOW_LOGS_DEFAULT = True
SHOW_IMAGE_DEFAULT = True
DEBUG = True

IMAGE_PREVIEW_WIDTH = 400
INFERENCE_LOG_PREFIX = "[OBB]"
OCR_LOG_PREFIX = "[OCR]"
OCR_CLASSES = {"entity", "attribute"}
